[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
'''
on_i = 1

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_source = '''
  autocmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

