[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    let g:molokai_original = 1
    let t_Co = 256
    let g:rehash256 = 1
    colorscheme molokai
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    noremap <C-p> :Denite file_rec<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  ctermbg=black
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=darkgrey
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'thinca/vim-zenspace'
hook_add = '''
    let g:zenspace#default_mode = 'on'
    autocmd! ColorScheme * highlight ZenSpace ctermbg=Red guibg=Red
'''

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_add = '''
    let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
    autocmd! BufWritePost * Neomake
'''

